"""
Part 5 — Synthetic Data Quality and Mode-Collapse Audit.

Implements rigorous quality checks, statistical divergence metrics,
and mode-collapse detection for synthetic minority samples generated by
SMOTE or QGAN.
"""
from __future__ import annotations

import logging
import numpy as np
from typing import Dict, Any, Tuple
from scipy import stats

logger = logging.getLogger(__name__)


# ── STEP 12: Mode Collapse Detection ──────────────────────────────────

def detect_mode_collapse(
    X_synthetic: np.ndarray,
    distance_threshold: float = 0.05,
    variance_threshold: float = 0.01,
) -> Dict[str, Any]:
    """
    Check whether the generator has collapsed into generating identical
    or near-identical samples.

    Metrics:
        - Mean pairwise Euclidean distance across synthetic samples
        - Average feature variance
        - Minimum pairwise distance
        - Ratio of unique samples
    """
    X_s = np.asarray(X_synthetic, dtype=np.float64)
    N, D = X_s.shape

    if N < 2:
        return {
            "status": "INSUFFICIENT_SAMPLES",
            "is_collapsed": False,
            "mean_pairwise_distance": 0.0,
            "avg_feature_variance": 0.0,
        }

    # 1. Feature variances
    feature_vars = np.var(X_s, axis=0)
    avg_var = float(np.mean(feature_vars))
    min_var = float(np.min(feature_vars))

    # 2. Pairwise distances (sample up to 200 pairs if N is large for speed)
    if N <= 300:
        # Exact all-pairs distance
        diff = X_s[:, np.newaxis, :] - X_s[np.newaxis, :, :]  # (N, N, D)
        dist_matrix = np.linalg.norm(diff, axis=-1)
        # Upper triangle only
        upper_indices = np.triu_indices(N, k=1)
        pairwise_dists = dist_matrix[upper_indices]
    else:
        # Monte-Carlo pairwise sample
        rng = np.random.RandomState(42)
        idx_a = rng.randint(0, N, size=1000)
        idx_b = rng.randint(0, N, size=1000)
        mask = idx_a != idx_b
        idx_a, idx_b = idx_a[mask], idx_b[mask]
        pairwise_dists = np.linalg.norm(X_s[idx_a] - X_s[idx_b], axis=-1)

    mean_dist = float(np.mean(pairwise_dists)) if len(pairwise_dists) > 0 else 0.0
    min_dist = float(np.min(pairwise_dists)) if len(pairwise_dists) > 0 else 0.0

    # 3. Decision rule
    is_collapsed = (mean_dist < distance_threshold) or (avg_var < variance_threshold)
    is_suspected = (mean_dist < distance_threshold * 2) or (avg_var < variance_threshold * 2)

    if is_collapsed:
        status = "COLLAPSED"
    elif is_suspected:
        status = "SUSPECTED"
    else:
        status = "HEALTHY"

    return {
        "status": status,
        "is_collapsed": is_collapsed,
        "mean_pairwise_distance": round(mean_dist, 4),
        "min_pairwise_distance": round(min_dist, 4),
        "avg_feature_variance": round(avg_var, 4),
        "min_feature_variance": round(min_var, 4),
        "n_synthetic_samples": N,
        "feature_dim": D,
    }


# ── STEP 11: Comprehensive Synthetic Data Quality Checks ───────────────

def evaluate_synthetic_quality(
    X_real_minority: np.ndarray,
    X_synthetic: np.ndarray,
    X_real_majority: np.ndarray | None = None,
) -> Dict[str, Any]:
    """
    Perform statistical quality checks comparing synthetic minority samples
    against real minority training samples.

    Checks:
        1. Range & numerical validity (no NaN/Inf)
        2. Mean vector difference (Euclidean distance)
        3. Standard deviation difference
        4. Correlation matrix Frobenius distance
        5. Kolmogorov-Smirnov 2-sample tests (distribution similarity per feature)
        6. Nearest real neighbor distance distribution
        7. Mode collapse audit
    """
    X_real = np.asarray(X_real_minority, dtype=np.float64)
    X_synth = np.asarray(X_synthetic, dtype=np.float64)

    assert not np.isnan(X_synth).any(), "Synthetic samples contain NaN values"
    assert not np.isinf(X_synth).any(), "Synthetic samples contain Infinite values"
    assert X_real.shape[1] == X_synth.shape[1], (
        f"Feature mismatch: real {X_real.shape[1]} vs synth {X_synth.shape[1]}"
    )

    D = X_real.shape[1]
    N_real = len(X_real)
    N_synth = len(X_synth)

    # 1. Mean and Std comparisons
    mean_real = np.mean(X_real, axis=0)
    mean_synth = np.mean(X_synth, axis=0)
    std_real = np.std(X_real, axis=0)
    std_synth = np.std(X_synth, axis=0)

    mean_diff_l2 = float(np.linalg.norm(mean_real - mean_synth))
    std_diff_l2 = float(np.linalg.norm(std_real - std_synth))

    # 2. Correlation matrix similarity (Frobenius distance)
    # Handle zero-variance features safely
    corr_real = np.corrcoef(X_real.T)
    corr_synth = np.corrcoef(X_synth.T)
    corr_real = np.nan_to_num(corr_real, nan=0.0)
    corr_synth = np.nan_to_num(corr_synth, nan=0.0)
    corr_frobenius_dist = float(np.linalg.norm(corr_real - corr_synth, ord="fro"))

    # 3. Two-sample Kolmogorov-Smirnov tests per feature
    ks_pvalues = []
    ks_statistics = []
    for d in range(D):
        res = stats.ks_2samp(X_real[:, d], X_synth[:, d])
        ks_statistics.append(float(res.statistic))
        ks_pvalues.append(float(res.pvalue))

    # Percentage of features where synthetic distribution is statistically indistinguishable (p > 0.05)
    matching_features_pct = round(
        float(np.mean([p > 0.05 for p in ks_pvalues])) * 100, 2
    )
    mean_ks_stat = round(float(np.mean(ks_statistics)), 4)

    # 4. Proximity to real minority samples
    # For each synthetic sample, distance to nearest real minority sample
    diff_real = X_synth[:, np.newaxis, :] - X_real[np.newaxis, :, :] # (N_synth, N_real, D)
    dists_to_real = np.min(np.linalg.norm(diff_real, axis=-1), axis=1) # (N_synth,)
    mean_dist_to_real = float(np.mean(dists_to_real))

    # 5. Proximity to real majority samples (if supplied)
    mean_dist_to_maj = None
    if X_real_majority is not None:
        X_maj = np.asarray(X_real_majority, dtype=np.float64)
        diff_maj = X_synth[:, np.newaxis, :] - X_maj[np.newaxis, :, :]
        dists_to_maj = np.min(np.linalg.norm(diff_maj, axis=-1), axis=1)
        mean_dist_to_maj = round(float(np.mean(dists_to_maj)), 4)

    # 6. Mode collapse check
    mode_collapse_report = detect_mode_collapse(X_synth)

    return {
        "n_real_minority": N_real,
        "n_synthetic": N_synth,
        "feature_dim": D,
        "mean_diff_l2": round(mean_diff_l2, 4),
        "std_diff_l2": round(std_diff_l2, 4),
        "correlation_frobenius_dist": round(corr_frobenius_dist, 4),
        "ks_stat_mean": mean_ks_stat,
        "ks_matching_features_pct": matching_features_pct,
        "mean_dist_to_nearest_real_minority": round(mean_dist_to_real, 4),
        "mean_dist_to_nearest_real_majority": mean_dist_to_maj,
        "mode_collapse": mode_collapse_report,
        "range_real": {
            "min": [round(float(v), 3) for v in np.min(X_real, axis=0)],
            "max": [round(float(v), 3) for v in np.max(X_real, axis=0)],
        },
        "range_synthetic": {
            "min": [round(float(v), 3) for v in np.min(X_synth, axis=0)],
            "max": [round(float(v), 3) for v in np.max(X_synth, axis=0)],
        },
    }
