"""
Security policies for model/artifact handling and data flow.

Covers:
- Safe model loading (warns about pickle/joblib code execution risk).
- Artifact integrity verification (SHA-256 checksums).
- File-level security policies (.gitignore enforcement, sensitive file detection).
- Data flow documentation utilities.
"""
from __future__ import annotations

import hashlib
import json
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional


# ── Trusted Artifact Assumption ──────────────────────────────────────
# IMPORTANT: joblib.load() and torch.load() can execute arbitrary code
# via Python's pickle protocol.  The MindMatrix project treats ALL
# artifacts in the models/ directory as trusted (they are generated by
# the pipeline itself).  If an untrusted party supplies model files,
# this assumption breaks and additional verification is required.
TRUSTED_ARTIFACT_DIRS = ["models", "artifacts"]

# Extensions that use pickle-based serialization (potential code execution)
PICKLE_EXTENSIONS = {".joblib", ".pkl", ".pickle", ".pth", ".pt"}

# Extensions that are safe (no code execution risk)
SAFE_EXTENSIONS = {".json", ".csv", ".npy", ".yaml", ".yml", ".md", ".txt"}


@dataclass
class ArtifactInfo:
    """Metadata about a model/pipeline artifact."""
    path: str
    filename: str
    extension: str
    size_bytes: int
    sha256: str
    uses_pickle: bool
    trusted: bool


def compute_file_hash(filepath: str, algorithm: str = "sha256") -> str:
    """
    Compute the cryptographic hash of a file.
    """
    h = hashlib.new(algorithm)
    with open(filepath, "rb") as f:
        while True:
            chunk = f.read(8192)
            if not chunk:
                break
            h.update(chunk)
    return h.hexdigest()


def inspect_artifact(filepath: str, trusted_dirs: Optional[List[str]] = None) -> ArtifactInfo:
    """
    Inspect a model/pipeline artifact and return its security metadata.
    """
    if trusted_dirs is None:
        trusted_dirs = TRUSTED_ARTIFACT_DIRS

    abspath = os.path.abspath(filepath)
    ext = os.path.splitext(abspath)[1].lower()
    is_trusted = any(
        td in abspath.replace("\\", "/")
        for td in trusted_dirs
    )

    return ArtifactInfo(
        path=abspath,
        filename=os.path.basename(abspath),
        extension=ext,
        size_bytes=os.path.getsize(abspath) if os.path.exists(abspath) else 0,
        sha256=compute_file_hash(abspath) if os.path.exists(abspath) else "",
        uses_pickle=ext in PICKLE_EXTENSIONS,
        trusted=is_trusted,
    )


def verify_artifact_integrity(filepath: str, expected_hash: str) -> bool:
    """
    Verify that a file matches its expected SHA-256 hash.
    """
    if not os.path.exists(filepath):
        return False
    actual = compute_file_hash(filepath)
    return actual == expected_hash


def generate_artifact_manifest(
    artifact_dir: str,
    output_path: Optional[str] = None,
) -> Dict[str, str]:
    """
    Generate a SHA-256 manifest of all artifacts in a directory.

    Returns dict of {filename: sha256_hash}.
    Optionally writes to a JSON file.
    """
    manifest = {}
    for fname in sorted(os.listdir(artifact_dir)):
        fpath = os.path.join(artifact_dir, fname)
        if os.path.isfile(fpath):
            manifest[fname] = compute_file_hash(fpath)

    if output_path:
        os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(manifest, f, indent=2)

    return manifest


# ── .gitignore Enforcement ───────────────────────────────────────────
# Files/patterns that MUST be in .gitignore for security
REQUIRED_GITIGNORE_ENTRIES = [
    ".env",
    "*.log",
    "logs/",
]

# Files/patterns that SHOULD be in .gitignore (recommended)
RECOMMENDED_GITIGNORE_ENTRIES = [
    "data/raw/",
    "models/",
    "artifacts/",
    "*.joblib",
    "*.pth",
    "*.pt",
]


def check_gitignore_compliance(project_root: str) -> Dict[str, Any]:
    """
    Check that .gitignore contains required security-related entries.

    Returns:
        Dictionary with 'compliant' flag, missing required entries,
        and missing recommended entries.
    """
    gitignore_path = os.path.join(project_root, ".gitignore")
    if not os.path.exists(gitignore_path):
        return {
            "compliant": False,
            "missing_required": REQUIRED_GITIGNORE_ENTRIES,
            "missing_recommended": RECOMMENDED_GITIGNORE_ENTRIES,
            "note": ".gitignore file not found",
        }

    with open(gitignore_path, "r", encoding="utf-8") as f:
        entries = {line.strip() for line in f if line.strip() and not line.startswith("#")}

    missing_required = [e for e in REQUIRED_GITIGNORE_ENTRIES if e not in entries]
    missing_recommended = [e for e in RECOMMENDED_GITIGNORE_ENTRIES if e not in entries]

    return {
        "compliant": len(missing_required) == 0,
        "missing_required": missing_required,
        "missing_recommended": missing_recommended,
    }


# ── Privacy-Preserving Data Flow ─────────────────────────────────────
DATA_FLOW_STAGES = [
    {
        "stage": "Input",
        "data_enters": "Raw clinical feature values (30 numeric measurements)",
        "data_leaves": "Validated feature vector",
        "access": "Input validation module",
        "identifier_handling": "Identity columns stripped before processing",
    },
    {
        "stage": "Preprocessing",
        "data_enters": "Validated feature vector (30D)",
        "data_leaves": "Scaled feature vector (30D)",
        "access": "Preprocessing pipeline (fitted scaler/imputer)",
        "identifier_handling": "No identifiers present",
    },
    {
        "stage": "Feature Extraction",
        "data_enters": "Scaled features (30D)",
        "data_leaves": "Latent representation (16D)",
        "access": "Autoencoder model",
        "identifier_handling": "No identifiers present; dimensionality reduced",
    },
    {
        "stage": "Feature Selection",
        "data_enters": "Latent features (16D)",
        "data_leaves": "Selected features (8D)",
        "access": "QAOA/Classical feature selector",
        "identifier_handling": "No identifiers present; further data minimization",
    },
    {
        "stage": "Quantum Classification",
        "data_enters": "Angle-encoded features (8D)",
        "data_leaves": "Probability score (benign vs malignant)",
        "access": "VQC model",
        "identifier_handling": "No identifiers present",
    },
    {
        "stage": "Response",
        "data_enters": "Classification probability",
        "data_leaves": "Predicted class, probability, risk assessment",
        "access": "Inference engine → API response",
        "identifier_handling": "No patient identifiers in response",
    },
]


def get_data_flow_diagram() -> str:
    """
    Generate a markdown data-flow diagram documenting what data
    enters and leaves each pipeline stage.
    """
    lines = ["# Privacy-Preserving Data Flow\n"]
    lines.append("| Stage | Data Enters | Data Leaves | Access | Identifier Handling |")
    lines.append("|-------|-------------|-------------|--------|---------------------|")
    for stage in DATA_FLOW_STAGES:
        lines.append(
            f"| {stage['stage']} | {stage['data_enters']} | "
            f"{stage['data_leaves']} | {stage['access']} | "
            f"{stage['identifier_handling']} |"
        )
    return "\n".join(lines)
